#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
PKG_DIR="openstack-helm"
STX_BASE=$(realpath ${MY_REPO}/stx)
SRC=$(realpath ${STX_BASE}/openstack-armada-app/${PKG_DIR})

mkdir -p ${PKG_BUILD_ROOT}
pushd ${PKG_BUILD_ROOT}

# Local mirror workaround until CGCS_BASE mirror is supported.
STX_MIRROR=$(realpath "/import/mirrors/starlingx")

# Download openstack-helm source package.
SHA="7803000a545687ec40b0ddc41d46a6b377dea45f"
OPENSTACK_PKG="openstack-helm-${SHA}.tar.gz"
OPENSTACK_SRC_PATH=$(realpath ${STX_MIRROR}/downloads/${OPENSTACK_PKG})
cp ${OPENSTACK_SRC_PATH} ${PKG_BUILD_ROOT}

# Extract the openstack-helm tar file.
tar xfz ${OPENSTACK_PKG}

# Copy source files to the build directory.
cp -pr ${SRC}/files/* ${PKG_BUILD_ROOT}
