#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: ironic
  labels:
    chart_group: openstack-ironic
spec:
  releaseName: osh-openstack-ironic
  chart:
    spec:
      chart: ironic
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: cinder
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: ironic-static-overrides
      valuesKey: ironic-static-overrides.yaml
    - kind: Secret
      name: ironic-system-overrides
      valuesKey: ironic-system-overrides.yaml
...
