#
# Copyright (c) 2022-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: ceph-rgw
  labels:
    chart_group: openstack-ceph-rgw
spec:
  releaseName: osh-openstack-ceph-rgw
  chart:
    spec:
      chart: ceph-rgw
      version: 0.1.27
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 1m
  timeout: 5m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: cinder
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: ceph-rgw-static-overrides
      valuesKey: ceph-rgw-static-overrides.yaml
    - kind: Secret
      name: ceph-rgw-system-overrides
      valuesKey: ceph-rgw-system-overrides.yaml
...
