#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: gnocchi
  labels:
    chart_group: openstack-gnocchi
spec:
  releaseName: osh-openstack-gnocchi
  chart:
    spec:
      chart: gnocchi
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: horizon
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: gnocchi-static-overrides
      valuesKey: gnocchi-static-overrides.yaml
    - kind: Secret
      name: gnocchi-system-overrides
      valuesKey: gnocchi-system-overrides.yaml
...
