#
# Copyright (c) 2022-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-keystone-api-proxy
labels:
  isApplication: false
endpoints:
  identity:
    force_public_endpoint: true
images:
  tags:
    keystone_api_proxy: docker.io/starlingx/stx-keystone-api-proxy:master-debian-stable-latest
    ks_endpoints: docker.io/starlingx/stx-heat:master-debian-stable-latest
    pre_apply_cleanup: docker.io/starlingx/stx-vault-manager:master-debian-stable-latest
network:
  keystone_api_proxy:
    ingress:
      classes:
        namespace: "nginx-openstack"
        cluster: "nginx"
conf:
  keystone_api_proxy:
    identity:
      bind_host: "::"
      remote_host: keystone.openstack.svc.cluster.local
      remote_port: 80
...
