---
- project:
    vars:
      ensure_tox_version: '<4'
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-openstack-tox-py39
        - k8sapp-openstack-tox-pylint
        - k8sapp-openstack-tox-flake8
        - k8sapp-openstack-tox-metadata
        - k8sapp-openstack-tox-pep8
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-openstack-tox-py39
        - k8sapp-openstack-tox-pylint
        - k8sapp-openstack-tox-flake8
        - k8sapp-openstack-tox-metadata
        - k8sapp-openstack-tox-pep8
    post:
      jobs:
        - stx-openstack-armada-app-upload-git-mirror

- job:
    name: k8sapp-openstack-tox-py39
    parent: openstack-tox-py39
    description: |
        Run py39 test for k8app-openstack
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
        - python3-k8sapp-openstack/k8sapp_openstack/*
    vars:
        tox_envlist: py39
        python_version: 3.9
        tox_extra_args: -c python3-k8sapp-openstack/k8sapp_openstack/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-openstack-tox-metadata
    parent: tox
    description: |
      Run metadata tests for k8sapp_oidc
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-openstack/k8sapp_openstack/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-openstack-tox-pylint
    parent: tox
    description: |
      Run pylint tests for k8sapp_oidc
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-openstack/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-openstack/k8sapp_openstack/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-openstack-tox-flake8
    parent: tox
    description: |
      Run flake8 tests for k8sapp_oidc
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-openstack/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-openstack/k8sapp_openstack/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-openstack-tox-pep8
    parent: tox
    description: |
      Run pep8 tests for k8sapp_openstack
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
    files:
      - python3-k8sapp-openstack/*
    vars:
      tox_envlist: pep8
      tox_extra_args: -c python3-k8sapp-openstack/k8sapp_openstack/tox.ini

- job:
    name: stx-openstack-armada-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/openstack-armada-app to
      github.com/starlingx/openstack-armada-app
    vars:
      git_mirror_repository: starlingx/openstack-armada-app
    secrets:
      - name: git_mirror_credentials
        secret: stx-openstack-armada-app-github-secret3
        pass-to-parent: true

- secret:
    name: stx-openstack-armada-app-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - E5N0XWLeyfmU0ZbsDl0HzhDJNPpnQtjEq/a0m53z9iSql6Cg+Lkab6QLZqM75pYhmkQmF
          6DDJR6IONQ09MWmnij/RC+S3C1Ym+YJYkXTC5D9lQUqjVmO2qMRuqNh4T5fHzi7Za/jPe
          Xz7o5oHAzj8ZEyzxtAIRB4HDIGex4yfGpTQ0rjAn9kUzpR/rKJkkRTuVEuJZDE6ZsDFad
          B+oji0hWWd7NY/MhLb/b7hFLqUr9exWY7xbG1n/bS39qKNgu7v9xdwj0bAnCyb2pTryiD
          YDgmPK3iNrJ70HktBQQuqVll2oVYQED7hVUOY2Wj5AYrwmI7B140dv0cnuYWA+3wwEQQY
          /ysjxsHY2jL7c/x2GJYp3oP8qj5gbBhH9Ec2/skVIA5rX7hJK7BGYfq5gXUktnpcRrd7B
          t9PHbxzoPpPnqIbp0z0l1p7fYy9nVzTKa44vRBPYnxEH4kAMgaEAY8D3jEbeUNy6R2SCp
          JQQjRcKBRiN8mbBbkgCWNxhpjWOn4JCcaYfQkesa0k+TifLcyOcKbdR0YsfkcfCbJUmG2
          JtTdIEFlbTYmh0nFCpFbUTiy1GzbQnrwLmOizFML9Mm2TbWmcGDJlrKEJ9WSVF8SJ79j8
          EQjGyMnDVpE2N2U8deukltCmnLOwNMq7zsPiTIYW6B03GyEFD3nf1N9q5/3XGU=
        - Ob00QhCwCaqJkOjZnUI94eygvy/J3bxsXV0And56/zQYTlvKB31O2TTOA/zx5UI1MNTh+
          oNOwVvUNoFfT2ZQEjxBB3hxpclLUM3xkP1R4no7pHWSBbmAJFt8uLghhx/4qzOQyjmcxd
          CkhEPkFoSMrby9T0Y/LM3zZ85gPWNbMJuBzLcZRSbBLSrd0kING/PH1w2Vrl6aru1FVZJ
          VLVkHjy58OY/4d2EAOdJ/cdkWdjfS5x77FduRirWdbZ8YqDg4IPgGZpVxvDl1CuqR5+39
          6n+Y/2s4BAhhhuC8ESDH48K/CGuvDWr6l5SaE6xRVlCZbuSgpH6otOCyaJdaZbGd1S9JR
          q3R5ZG6xoENtlUWcAdRq9p2V2uTHIFGvj6xbH/xAbqKfFeEL6WNZ0F6bNKImBBULP2kOp
          VT0K/kCn/Fk/CrSz2yfrn25sCX5ryd2nIWNl3li6kJjWxNZ5gSdgPRtn9aTrEmvpX05Yq
          GBXCj8My5htsjTGWIEOfi03182tOXEQKtpWL6HzYWYfpV0yvhd+dWWsc8YXO5Ic4lOHJB
          tKbFiDnc/38rNhKZDONhXpitHNMpKJ/D6+SE1kdr/9Bvt/D5KMNu2yLdd4Wch44oTa6gZ
          Q+moIk7Rl4ed1wcIslfxnYocYnoOVIj3YydVPRPcxa2/T1ZhnV8NrbE8zz4xY4=
        - ZgpQTwWZCV0tG9DndaiuhCPJT0LGTAuLTJEHW6JvqNvGrViDZ3isMlRfmQjbAnrYZFWin
          PWVjJ9V7FGrPWpY1FVRIQHnb05EHCVT8KW31dZJY15OLtBbNZwJabSFTLcDXD8bE35Mvy
          kvZzWTYhKLdU4ZUZg+/fRNAnRHYt/sL789L/NyjEFGnMsMJdnI5IEMFRfuW9vlc5Fbbgv
          ykIssRMYMOyE5c0CZtZ6czzp7PLekswU5VbD1xNBjUhERHFPD9DSwYsbQa76xrfg7vkG2
          Em1D0zJ2YQ4UkCoSlqVORc8rCVu7ANyzvr/9Veq0bP2yviaNpMhjw/GXcUJg6SYhGoDrY
          8Ce06psF55mQ5F5merxLBiCR5dymdQN/tUane3GY48LSugiIi34QuYQwvN1h0IAS6VdtA
          YBRwqjnJvp+Zm7b8jsvPFMiZ0W+a8aOndOUGz443McclS9hIIZEewxTfxSQcDsf3U9NdM
          KsydKVOzCe6p2RVeaL9/BJw5qYDYP1XgxhHXtffbcxaxZ4kDu5c0tFxmKHyMFnnSQ+ooi
          JVJjqtxGZwRM3DDndd8b1rerfpNAUidlfV0aTIUwxjmnCkGP2JqwaGJP+PdgRiW9ugwqy
          F/PUFrBBtqyorcnnXSY+cHhLvoPaGJFxPYrskWuk05jpxqPLuZyvWmI3rd8hto=
        - XmPIydLkuHkUE15FrjdMWWRsUpTvgAss8ircsnOBtar4kB1MQpobA7SH7QKfIaRv9+D70
          Fe2ohU7WDploP1f1WsgEyA5626xXG927YUWGjK2PQ251+KX6qUVCo+Nr/hK3Vke1yAcI/
          zHu/73IOKgY3rfUp/LPAVSblQDEuA/boXW9lKqRSntjz8Sp9Siu2XTwC57lGFxZnoa/5/
          FdhBcFU/9M9ySktZicRQB796a9mdzVDDgElvfUcvft+LjlQOVxJKLsROOUpZHCOB657a3
          aZDSt48rVQRHB5NGGiYCQGai+Qy230tVux/iufoA4dyZ93sZrQsG5PZ5jkbLwAZHJ4nUl
          k//fFdMFtL4Dz6H+FjBiOGCcWL8fxjvF2SnUDfrO5+ogT5URPFqCAAwMovfgBYnVhdR2f
          0gRRwdqLFnEty0jfgubwGl6E0WTECH/tjAvzm+uJcwX12EEFVgE73yHSADz0zMMNFTaWE
          9rmhE6mOnMY3gbr4SOxTobrKIU/bebXxO7ukC1Q2eAtUmEIuBipMba6lheR/hRWQVXtXK
          pHVQZb9UUERaRP4aTivFkiXHJviJKt7ldBHzZhS6KyHhjYkmRknVfVMG/+BHfP5vCB4eQ
          sxwvDa5JZ+nM8Ca8y/XWlXWWAD8Y0soP9CcTRdDDrVYJxvvbZtDCaJX3XNQULc=
        - U9Y5yITJMLUxXCTnk3VlKWe4Qye0NHvuPjgY+oTm4JSIGiQyTTjwH74manmhI0FAie7VA
          C4wlJYZxqKI7aF/BXAtjOSYMpZox/7jWwmr/aB/NF0vBHLVTvu5Jws85Z1Ocy8UrtEGPd
          xSiIE5cgg8zlevu7gisgzCPkOFK+KCgHlRXo4tHkcj7WIAtFlyj1dmxPxCZM55P+wfkIK
          drV22l8vGNFDoZqBj+zrdPofYv+1nnyz+U4PmJEXTWDIgcNq59AEpgvbSaR1WUCqYjKS7
          T9QzIF9wPeZUPLkt8i7Ejoor9gob0ebQQArePSnv/44ksHOuuB8YmgbdRtIfel2WcQPc8
          xG7iZbkx1ec7x5vFAn3LYGDvwPYTSly7Os/ElkMrfXPh1XKfM5DUfL6yCemBXlVW7xqnr
          oUFzt5WbTUPoTpthG1aZEpsXXcdoQxMSE5pg88hAfK/K9w0fmPl76AkWqz8dODVYTxoJb
          6IsVAqkysdWHWsOonVR1l8CZTJx7kdRCexTgStaSu9zIRAn6oylcTqF5MUSS4jYWCS2CH
          AhYhZzGiVGD/3atHI9VCPl6fKiFp+SDE2rO6xmz4dELWpXbOFRQ8UDRxSgru+mXFCJYXu
          yAPz4X6vn6+EryIfnVjXoVpQXgP8yDpZhpbDpy09xXpkQiyjyN0LfZM6YXaokA=
        - iPWHAUPN+q7u9KopNWHkQt/Mq0qUJuR645LH9qqOZQwDRZ9VL7pq6kBwK3+B3wtdUn6Z5
          uDOn2h5LbnY3o4YY6JcwkuWe0OV84tLiLF54Kr8L7JkJSTkaXllgu4w9qc4h0seNNMevf
          EZvchd0tu35aqcI/0qYF2O9U3ypt7CEHfDQyrpOtGcWHXbaKs5Ub0dnnJMC6LDOFbwrGs
          Xv0n17i4Y3XpeRNKfmI6c3c/9xr8tWSn71mxBApVks/2gtQblPyHP0bBZ7FEX3Wft8KEP
          lFDK8hAdXO5f4a9FzzgSa5D8+b3aHEHqcnawEiCULZcAqNOblTHeb29Qt9ZV0/OMpkuEK
          NI72Ju/Dq/PFsuPsC0PpyGVmrcQh5iIWKE8vWW5oZqK+hgtlmy1Ubwmk9H5gk/o1JFd5I
          kWxcZjd3Z3twlyo7SHufc+GVF4ibcNixeSoLMK5XlXrUdRiL7TEBMcevKvcAjDfE22Ipp
          eR5EDvRyYiNVx1hTr2EZCLKCkA3TZkiYSfEdx3Ys6CiTjPCwRFq0rOHcKhGSfGX+qI3NR
          VvWndMOHLzjnv4SLB1eA6w5EbX1S31WVTikqiqI6GyR1mxi6LrOtpJ/DwDmSHD/XHgqZb
          SxgG72HjE3gnUHo20IUlUMciagszYYcP0AC2Ln9+f0vQv1JHzKIrSrgVtzPvQw=
        - np4Dw6VusTYVge++VKxBCGEBj4FZ9UsutMoYNMRM7elVjV/69bnm0pY2efNy61UZwyLJ8
          5wCgmu+HMuwIP9aomvGJv5Y5KYvvgfVKyDlSrqs/ewn2RQ2sLSz5W6ZgrHtWuRay4l5xy
          ztAJDv+j1B7dQznnBOZOgStIgJ0nYxe0cvkDjszNqou9A/4eV3mH7ahrpEY6rTsppmJ3b
          0j3v5zkDc2h2VMwV0l92HEbt1Dfoy1ar3dV8FKI3T6s67+PFEiaoG7FAtO8jHFSvBqnoG
          l6A7EN9z/MFpybzI/0zkO98yiL0Tdq0f4XtcL0+tnipxlcs95bBGH2LgNw1IjVIHo62YD
          JHIjYhbJsF4j+o0xctaP9/YgiZHLsYnOdkal4u2pmRPGwRrwopM9CLmetgq5pjqrlKcpV
          NGnu6h+7aAij7mLWCDKFlNUF0ufMTX5+wWDJvoN30ERXqv8qXDVQtGca67u+4+Eogp/31
          qPkueICkHt7KgnNuEw0Xq1hw2tMtLr7xShG7nlHiQ5sukufIqaTikjOe1NlbxCWuuRFIW
          PnAVomC+daWP6qFq50MKEiJ7doqlq0SXR5lh1c6ebjCx29IqfsZo2oOd6aP9Wfz4LVqyN
          gQddJ9tC0X8a1wSwiNcX46bESfo6Np+9lNZO+X7jJ53cCY+acy5/pSGxBma/jI=
