upstream/openstack/openstack-aodh
upstream/openstack/openstack-ironic
upstream/openstack/python-barbican
upstream/openstack/python-ceilometer
upstream/openstack/python-cinder
upstream/openstack/python-glance
upstream/openstack/python-heat/openstack-heat
upstream/openstack/python-horizon
upstream/openstack/python-keystone
upstream/openstack/python-neutron
upstream/openstack/python-nova
upstream/openstack/python-openstackclient
upstream/openstack/python-placement

