#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-ingress
labels:
  server:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  error_server:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
images:
  tags:
    image_repo_sync: null
    ingress_module_init: null
    ingress_routed_vip: null
    keepalived: null
pod:
  replicas:
    error_page: 2
    ingress: 2
  affinity:
    anti:
      type:
        default: requiredDuringSchedulingIgnoredDuringExecution
  tolerations:
    ingress:
      enabled: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: openstack-compute-node
        operator: Exists
        effect: NoSchedule
conf:
  ingress:
    worker-processes: '4'
    bind-address: "::"
...
