#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
namespace: openstack
commonLabels:
  chart_group: openstack-ingress
resources:
  - helmrelease.yaml
secretGenerator:
  - name: ingress-static-overrides
    files:
      - ingress-static-overrides.yaml
  - name: ingress-system-overrides
    files:
      - ingress-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
...
