#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: nova-api-proxy
  labels:
    chart_group: openstack-nova-api-proxy
spec:
  releaseName: osh-openstack-nova-api-proxy
  chart:
    spec:
      chart: nova-api-proxy
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: placement
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: nova-api-proxy-static-overrides
      valuesKey: nova-api-proxy-static-overrides.yaml
    - kind: Secret
      name: nova-api-proxy-system-overrides
      valuesKey: nova-api-proxy-system-overrides.yaml
...
