#
# Copyright (c) 2022-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-nova-api-proxy
labels:
  isApplication: false
images:
  tags:
    nova_api_proxy: docker.io/starlingx/stx-nova-api-proxy:master-debian-stable-latest
    ks_endpoints: docker.io/starlingx/stx-heat:master-debian-stable-latest
    pre_apply_cleanup: docker.io/starlingx/stx-vault-manager:master-debian-stable-latest
endpoints:
  identity:
    force_public_endpoint: true
network:
  api_proxy:
    ingress:
      classes:
        namespace: "nginx-openstack"
        cluster: "nginx"
pod:
  affinity:
    anti:
      type:
        default: requiredDuringSchedulingIgnoredDuringExecution
  tolerations:
    nova_api_proxy:
      enabled: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: openstack-compute-node
        operator: Exists
        effect: NoSchedule
    nova:
      enabled: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: openstack-compute-node
        operator: Exists
        effect: NoSchedule
  resources:
    enabled: true
    api_proxy:
      requests:
        ephemeral-storage: "10000Ki"
conf:
  nova_api_proxy:
    DEFAULT:
      osapi_proxy_listen: "::"
      nfvi_compute_listen: "::"
      osapi_compute_listen: nova-api-internal.openstack.svc.cluster.local
      osapi_compute_listen_port: 80
    keystone_authtoken:
      interface: internal
      auth_uri: http://keystone.openstack.svc.cluster.local:80/v3
      auth_url: http://keystone.openstack.svc.cluster.local:80/v3
...
