#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: starlingx
spec:
  url: http://192.168.206.1:8080/helm_charts/starlingx
  interval: 60m
...
