#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-barbican
labels:
  api:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
images:
  tags:
    barbican_api: docker.io/starlingx/stx-barbican:master-centos-stable-latest
    barbican_db_sync: docker.io/starlingx/stx-barbican:master-centos-stable-latest
    bootstrap: docker.io/starlingx/stx-heat:master-centos-stable-latest
    db_drop: docker.io/starlingx/stx-heat:master-centos-stable-latest
    db_init: docker.io/starlingx/stx-heat:master-centos-stable-latest
    image_repo_sync: null
    ks_endpoints: docker.io/starlingx/stx-heat:master-centos-stable-latest
    ks_service: docker.io/starlingx/stx-heat:master-centos-stable-latest
    ks_user: docker.io/starlingx/stx-heat:master-centos-stable-latest
    scripted_test: docker.io/starlingx/stx-heat:master-centos-stable-latest
pod:
  replicas:
    api: 2
  affinity:
    anti:
      type:
        default: requiredDuringSchedulingIgnoredDuringExecution
  tolerations:
    barbican:
      enabled: true
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: openstack-compute-node
          operator: Exists
          effect: NoSchedule
endpoints:
  oslo_messaging:
    statefulset:
      name: osh-openstack-rabbitmq-rabbitmq
  identity:
    force_public_endpoint: true
conf:
  barbican:
    barbican_api:
      bind_host: "::"
    keystone_authtoken:
      auth_uri: http://keystone.openstack.svc.cluster.local:80/v3
      auth_url: http://keystone.openstack.svc.cluster.local:80/v3
...
