#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: barbican
  labels:
    chart_group: openstack-barbican
spec:
  releaseName: osh-openstack-barbican
  chart:
    spec:
      chart: barbican
      version: 0.2.7
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 1m
  timeout: 30m
  test:
    enable: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: keystone
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: barbican-static-overrides
      valuesKey: barbican-static-overrides.yaml
    - kind: Secret
      name: barbican-system-overrides
      valuesKey: barbican-system-overrides.yaml
...
