#
# Copyright (c) 2022-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-dcdbsync
labels:
  isApplication: false
images:
  tags:
    dcdbsync: docker.io/starlingx/stx-keystone:master-debian-stable-latest
    ks_endpoints: docker.io/starlingx/stx-heat:master-debian-stable-latest
    pre_apply_cleanup: docker.io/starlingx/stx-vault-manager:master-debian-stable-latest
...
