#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: dcdbsync
  labels:
    chart_group: openstack-dcdbsync
spec:
  releaseName: osh-openstack-dcdbsync
  chart:
    spec:
      chart: dcdbsync
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: cinder
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: dcdbsync-static-overrides
      valuesKey: dcdbsync-static-overrides.yaml
    - kind: Secret
      name: dcdbsync-system-overrides
      valuesKey: dcdbsync-system-overrides.yaml
...
