#
# Copyright (c) 2022-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: cinder
  labels:
    chart_group: openstack-cinder
spec:
  releaseName: osh-openstack-cinder
  chart:
    spec:
      chart: cinder
      version: 0.3.11
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
    disableWait: true
  upgrade:
    disableHooks: false
    disableWait: true
  dependsOn:
    - name: glance
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: cinder-static-overrides
      valuesKey: cinder-static-overrides.yaml
    - kind: Secret
      name: cinder-system-overrides
      valuesKey: cinder-system-overrides.yaml
...
