#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: pci-irq-affinity-agent
  labels:
    chart_group: openstack-pci-irq-affinity-agent
spec:
  releaseName: osh-openstack-pci-irq-affinity-agent
  chart:
    spec:
      chart: pci-irq-affinity-agent
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: nova
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: pci-irq-affinity-agent-static-overrides
      valuesKey: pci-irq-affinity-agent-static-overrides.yaml
    - kind: Secret
      name: pci-irq-affinity-agent-system-overrides
      valuesKey: pci-irq-affinity-agent-system-overrides.yaml
...
