#
# Copyright (c) 2022-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-pci-irq-affinity-agent
labels:
  isApplication: false
images:
  tags:
    pci_irq_affinity_agent: docker.io/starlingx/stx-pci-irq-affinity-agent:@IMAGE_PREFIX@-@OS@-@OS_CODENAME@-@OS_ARCH@-@BUILD_STREAM@-@IMAGE_SUFFIX@
    dep_check: quay.io/airshipit/kubernetes-entrypoint:7a6a594d2efec8b402ad970d18906863b2f04d4f-ubuntu_noble
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: openstack-compute-node
    operator: Exists
    effect: NoSchedule
pod:
  labels:
    include_app_kubernetes_io: false
...
