#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: memcached
  labels:
    chart_group: openstack-memcached
spec:
  releaseName: osh-openstack-memcached
  chart:
    spec:
      chart: memcached
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: False
  upgrade:
    disableHooks: False
  dependsOn:
    - name: mariadb
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: memcached-static-overrides
      valuesKey: memcached-static-overrides.yaml
    - kind: Secret
      name: memcached-system-overrides
      valuesKey: memcached-system-overrides.yaml
...
