#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack
resources:
  - base
  - psp-rolebinding
  - ingress
  - nginx-ports-control
  - mariadb
  - garbd
  - memcached
  - rabbitmq
  - barbican
  - keystone
  - keystone-api-proxy
  - glance
  - cinder
  - ceph-rgw
...
