#
# Copyright (c) 2023-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: clients
  labels:
    chart_group: clients
spec:
  releaseName: osh-openstack-clients
  chart:
    spec:
      chart: clients
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: heat
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: clients-static-overrides
      valuesKey: clients-static-overrides.yaml
    - kind: Secret
      name: clients-system-overrides
      valuesKey: clients-system-overrides.yaml
...
