#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
fullnameOverride: ingress-nginx

controller:
  config:
    bind-address: '::'
    worker-processes: "4"
    enable-underscores-in-headers: "true"
    enable-vts-status: "true"
    proxy-connect-timeout: "30"
    server-tokens: "false"
    ssl-dh-param: openstack/secret-dhparam

  dnsPolicy: ClusterFirstWithHostNet
  ingressClassResource:
    enabled: false
    controllerValue: k8s.io/ingress-nginx-openstack
  scope:
    enabled: true
    namespace: "openstack"
    namespaceSelector: "openstack"
  labels:
    app: ingress-api
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "openstack-compute-node"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: release_group
              operator: In
              values:
              - osh-openstack-ingress
            - key: application
              operator: In
              values:
              - ingress
            - key: component
              operator: In
              values:
              - server
        topologyKey: kubernetes.io/hostname
  nodeSelector:
    openstack-control-plane: "enabled"
  service:
    type: ClusterIP
  admissionWebhooks:
    enabled: false
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  requests:
    cpu: 100m
    ephemeral-storage: 2000Ki
    memory: 128Mi

defaultBackend:
  enabled: true
  config:
    bind-address: '::'
    worker-processes: "4"
    enable-underscores-in-headers: "true"
    enable-vts-status: "true"
    proxy-connect-timeout: "30"
    server-tokens: "false"
    ssl-dh-param: openstack/secret-dhparam

  dnsPolicy: ClusterFirstWithHostNet
  ingressClassResource:
    enabled: false
    controllerValue: k8s.io/ingress-nginx-openstack
  scope:
    enabled: true
    namespace: "openstack"
    namespaceSelector: "openstack"
  labels:
    app: ingress-api
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "openstack-compute-node"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: release_group
              operator: In
              values:
              - osh-openstack-ingress
            - key: application
              operator: In
              values:
              - ingress
            - key: component
              operator: In
              values:
              - server
        topologyKey: kubernetes.io/hostname
  nodeSelector:
    openstack-control-plane: "enabled"
  service:
    type: ClusterIP
  admissionWebhooks:
    enabled: false
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  requests:
    cpu: 100m
    ephemeral-storage: 2000Ki
    memory: 128Mi

revisionHistoryLimit: 3
...
