#
# Copyright (c) 2022-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: nginx-ports-control
  labels:
    chart_group: openstack-nginx-ports-control
spec:
  releaseName: osh-openstack-nginx-ports-control
  chart:
    spec:
      chart: nginx-ports-control
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 1m
  timeout: 30m
  test:
    enable: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: nginx-ports-control-static-overrides
      valuesKey: nginx-ports-control-static-overrides.yaml
    - kind: Secret
      name: nginx-ports-control-system-overrides
      valuesKey: nginx-ports-control-system-overrides.yaml
...
