#
# Copyright (c) 2022-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: ceilometer
  labels:
    chart_group: openstack-ceilometer
spec:
  releaseName: osh-openstack-ceilometer
  chart:
    spec:
      chart: ceilometer
      version: 0.2.11
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: horizon
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: ceilometer-static-overrides
      valuesKey: ceilometer-static-overrides.yaml
    - kind: Secret
      name: ceilometer-system-overrides
      valuesKey: ceilometer-system-overrides.yaml
...
