{{/*
#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- define "clients.daemonset" }}
{{- $daemonset := index . 0 }}
{{- $configMapName := index . 1 }}
{{- $serviceAccountName := index . 2 }}
{{- $envAll := index . 3 }}
{{- with $envAll }}

{{- $mounts_clients := .Values.pod.mounts.clients.clients }}
{{- $mounts_clients_init := .Values.pod.mounts.clients.init_container }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: clients
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll "clients" "clients" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  selector:
    matchLabels:
{{ tuple $envAll "clients" "clients" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "clients" "clients" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
{{ dict "envAll" . "application" "clients" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      serviceAccountName: {{ $serviceAccountName }}
      nodeSelector:
        {{ .Values.labels.openstack_clients.node_selector_key }}: {{ .Values.labels.openstack_clients.node_selector_value }}
      tolerations:
{{ toYaml .Values.pod.tolerations.clients.tolerations | indent 8 }}
      initContainers:
{{ tuple $envAll "pod_dependency" $mounts_clients_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: clients-init
{{ tuple $envAll "openstack_clients" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" . "application" "clients" "container" "clients_init" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          command:
            - /tmp/clients-init.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: clients-bin
              mountPath: /tmp/clients-init.sh
              subPath: clients-init.sh
              readOnly: true
            - name: clients-bin
              mountPath: /tmp/clients-wrapper.sh
              subPath: clients-wrapper.sh
              readOnly: true
            - name: clients-bin
              mountPath: /tmp/clear-aliases.sh
              subPath: clear-aliases.sh
              readOnly: true
            - name: clients-bin
              mountPath: /tmp/setup-aliases.sh
              subPath: setup-aliases.sh
              readOnly: true
            - name: clients-bin
              mountPath: /tmp/local_openstackrc
              subPath: local_openstackrc
              readOnly: true
            - name: host-var-opt
              mountPath: /var/opt
      containers:
        - name: clients
{{ tuple $envAll "openstack_clients" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" . "application" "clients" "container" "clients" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          {{ if .Values.manifests.certificates }}
          env:
          - name: OS_CACERT
            value: "/etc/ssl/certs/openstack-helm.crt"
          {{ end }}
          command:
          - /bin/bash
          stdin: true
          workingDir: /wd
          volumeMounts:
            - name: host-var-opt-openstack
              mountPath: /wd
{{- dict "enabled" .Values.manifests.certificates "name" .Values.secrets.tls.clients.api.public | include "helm-toolkit.snippets.tls_volume_mount" | indent 12 }}
{{ if $mounts_clients.volumeMounts }}{{ toYaml $mounts_clients.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: clients-bin
          configMap:
            name: clients-bin
            defaultMode: 0555
        - name: host-var-opt
          hostPath:
            path: /var/opt
            type: Directory
        - name: host-var-opt-openstack
          hostPath:
            path: /var/opt/openstack
            type: DirectoryOrCreate
{{- dict "enabled" .Values.manifests.certificates "name" .Values.secrets.tls.clients.api.public | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{ if $mounts_clients.volumes }}{{ toYaml $mounts_clients.volumes | indent 8 }}{{ end }}
{{- end }}
{{- end }}

{{- if .Values.manifests.daemonset_clients }}
{{- $envAll := . }}
{{- $daemonset := "clients" }}
{{- $configMapName := "clients-etc" }}
{{- $serviceAccountName := "clients" }}
{{- $dependencyOpts := dict "envAll" $envAll "dependencyKey" "clients" -}}
{{- $_ := include "helm-toolkit.utils.dependency_resolver" $dependencyOpts | toString | fromYaml }}
{{ tuple $envAll "pod_dependency" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
{{- $daemonset_yaml := list $daemonset $configMapName $serviceAccountName . | include "clients.daemonset" | toString | fromYaml }}
{{- $configmap_yaml := "clients.configmap.etc" }}
{{- list $daemonset $daemonset_yaml $configmap_yaml $configMapName . | include "helm-toolkit.utils.daemonset_overrides" }}
{{- end }}

