#
# Copyright (c) 2024-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: ingress-nginx-openstack
  labels:
    chart_group: ingress-nginx-openstack
spec:
  releaseName: ingress-nginx-openstack
  chart:
    spec:
      chart: ingress-nginx-openstack
      version: 4.12.1+STX.1
      sourceRef:
        kind: HelmRepository
        name: starlingx
      interval: 1m
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: ingress-nginx-static-overrides
      valuesKey: ingress-nginx-static-overrides.yaml
    - kind: Secret
      name: ingress-nginx-system-overrides
      valuesKey: ingress-nginx-system-overrides.yaml
...
