#
# Copyright (c) 2023-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-glance
labels:
  isApplication: false
  api:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  registry:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
images:
  tags:
    bootstrap: docker.io/starlingx/stx-heat:master-debian-stable-latest
    db_drop: docker.io/starlingx/stx-heat:master-debian-stable-latest
    db_init: docker.io/starlingx/stx-heat:master-debian-stable-latest
    dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    glance_api: docker.io/starlingx/stx-glance:master-debian-stable-latest
    glance_db_sync: docker.io/starlingx/stx-glance:master-debian-stable-latest
    glance_metadefs_load: docker.io/starlingx/stx-glance:master-debian-stable-latest
    glance_storage_init: docker.io/openstackhelm/ceph-config-helper:ubuntu_bionic-20201223
    image_repo_sync: null
    ks_endpoints: docker.io/starlingx/stx-heat:master-debian-stable-latest
    ks_service: docker.io/starlingx/stx-heat:master-debian-stable-latest
    ks_user: docker.io/starlingx/stx-heat:master-debian-stable-latest
    rabbit_init: docker.io/rabbitmq:3.9.0-management
    pre_apply_cleanup: docker.io/starlingx/stx-vault-manager:master-debian-stable-latest
    test: null
pod:
  replicas:
    api: 2
    registry: 2
  affinity:
    anti:
      type:
        default: requiredDuringSchedulingIgnoredDuringExecution
  tolerations:
    glance:
      enabled: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: openstack-compute-node
        operator: Exists
        effect: NoSchedule
endpoints:
  oslo_messaging:
    statefulset:
      name: osh-openstack-rabbitmq-rabbitmq
  identity:
    force_public_endpoint: true
conf:
  extra_metadata:
    pci_irq_affinity:
      description: "This provides the possibility to set custom PCI IRQ Affinity configuration for instances with dedicated vCPUs."
      display_name: PCI IRQ Affinity
      namespace: OS::Compute::PCIIRQAffinity
      properties:
        pci_irq_affinity_mask:
          description: "Determines which vCPUs assigned to the instance must handle the interrupts from the PCI devices. The expected mask is a comma-separated list of values that can be expressed as: a single vCPU index (int), a closed interval of vCPU indexes (int1-int2), and a negation expressing that the vCPU index will not be assigned (^int). Note: int must be an integer between 0 and flavor.vcpus - 1. Example: 0-3,^2,6 means that vCPUs with indexes 0,1,3 and 6 will be assigned."
          title: PCI IRQ Affinity Mask
          type: string
      protected: true
      resource_type_associations:
        - name: OS::Nova::Flavor
          prefix: 'hw:'
        - name: OS::Glance::Image
          prefix: 'hw_'
        - name: OS::Cinder::Volume
          prefix: 'hw_'
          properties_target: image
      visibility: public
  glance:
    DEFAULT:
      bind_host: "::"
      registry_host: glance-reg.openstack.svc.cluster.local
      registry_port: 80
    keystone_authtoken:
      auth_uri: http://keystone.openstack.svc.cluster.local:80/v3
      auth_url: http://keystone.openstack.svc.cluster.local:80/v3
  glance_registry:
    keystone_authtoken:
      auth_uri: http://keystone.openstack.svc.cluster.local:80/v3
      auth_url: http://keystone.openstack.svc.cluster.local:80/v3
...
