#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: glance
  labels:
    chart_group: openstack-glance
spec:
  releaseName: osh-openstack-glance
  chart:
    spec:
      chart: glance
      version: 0.2.9
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 5m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
    disableWait: true
  upgrade:
    disableHooks: false
    disableWait: true
  dependsOn:
    - name: keystone
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: glance-static-overrides
      valuesKey: glance-static-overrides.yaml
    - kind: Secret
      name: glance-system-overrides
      valuesKey: glance-system-overrides.yaml
...
