#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
namespace: openstack
resources:
  - helmrelease.yaml
secretGenerator:
  - name: glance-static-overrides
    files:
      - glance-static-overrides.yaml
  - name: glance-system-overrides
    files:
      - glance-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
...
