#
# Copyright (c) 2022-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-garbd
labels:
  isApplication: false
  server:
    node_selector_key: openstack-compute-node
    node_selector_value: enabled
jobs:
  ttlSecondsAfterFinished: 5400
pod:
  tolerations:
    garbd:
      enabled: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: openstack-compute-node
        operator: Exists
        effect: NoSchedule
images:
  tags:
    garbd: docker.io/starlingx/stx-mariadb:master-debian-stable-latest
    image_repo_sync: null
...
