#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-garbd
labels:
  server:
    node_selector_key: openstack-compute-node
    node_selector_value: enabled
pod:
  tolerations:
    garbd:
      enabled: true
      tolerations:
      - key: openstack-compute-node
        operator: Exists
        effect: NoSchedule
images:
  tags:
    garbd: docker.io/starlingx/stx-mariadb:master-centos-stable-latest
    image_repo_sync: null
...
