#
# Copyright (c) 2022-2026 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
release_group: osh-openstack-garbd
labels:
  isApplication: false
  server:
    node_selector_key: openstack-compute-node
    node_selector_value: enabled
    node_selector_exclude_key: openstack-control-plane
    node_selector_exclude_value: enabled
pod:
  labels:
    include_app_kubernetes_io: false
  tolerations:
    garbd:
      enabled: true
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: openstack-compute-node
        operator: Exists
        effect: NoSchedule
images:
  tags:
    garbd: docker.io/starlingx/stx-mariadb:@IMAGE_PREFIX@-@OS@-@OS_CODENAME@-@OS_ARCH@-@BUILD_STREAM@-@IMAGE_SUFFIX@
    pre_apply_cleanup: docker.io/starlingx/stx-vault-manager:@IMAGE_PREFIX@-@OS@-@OS_CODENAME@-@OS_ARCH@-@BUILD_STREAM@-@IMAGE_SUFFIX@
    image_repo_sync: null
    dep_check: quay.io/airshipit/kubernetes-entrypoint:7a6a594d2efec8b402ad970d18906863b2f04d4f-ubuntu_noble
...
